version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    secrets:
      - db_root_password
      - db_name
      - db_user_name
      - db_password
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/db_root_password
      - MYSQL_PASSWORD=/run/secrets/db_password
      - MYSQL_DATABASE=/run/secrets/db_name
      - MYSQL_USER=/run/secrets/db_user_name

  redis:
    image: redis:alpine
    restart: always

  app:
    build: ./rengacloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data
      - theme:/var/www/html/themes/rengacloud
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/rengacloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/rengacloud_admin_user
      - MYSQL_DATABASE=/run/secrets/db_name
      - MYSQL_USER=/run/secrets/db_user_name
    depends_on:
      - db
      - redis
    secrets:
      - rengacloud_admin_password
      - rengacloud_admin_user
      - db_name
      - db_user_name

  web:
    build: ./web
    restart: always
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
  apps:
  config:
  data:
  theme:
  
secrets:
  db_root_password:
    file: ./db_root_password.txt
  db_password:
    file: ./db_password.txt
  rengacloud_admin_password:
    file: ./rengacloud_admin_password.txt
  rengacloud_admin_user:
    file: ./rengacloud_admin_user.txt
  db_name:
    file: ./db_name.txt
  db_user_name:
    file: ./db_user_name.txt
